
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'GuardianChild360' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Pods for GuardianChild360
  pod 'Firebase/Core', '~> 8.0.0'
  pod 'Firebase/Auth', '~> 8.0.0'
  pod 'Firebase/Firestore', '~> 8.0.0'
  pod 'Firebase/Storage', '~> 8.0.0'

  # Pods for react-native-webrtc
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
